### PR TITLE
Update demon-editor.po Italian

### PR DESCRIPTION
**Pull request by mapi68**

### CODE REVIEW

**Comment by DYefremov** [comment]
Hello. 
I don't speak Italian, but after checking with several online translators, I have some questions. 
For example, abbreviated names. Strings: 30, 36, 42, 45, 1062.
In addition, you need to clarify the meaning of the following lines. Maybe they convey the wrong meaning. Strings: 684, 927, 1038, 1224, 1257.
Also line 14 should be left as is. 

Please check again. Thanks!

**Comment by mapi68** [comment]
Hello,

>>> For example, abbreviated names. Strings: 30, 36, 42, 45, 1062.
Italian is a very verbose language compared to English, so it isn't better use abbreviated names.

>>> In addition, you need to clarify the meaning of the following lines. Maybe they convey the wrong meaning. Strings: 684, 927, 1038, 1224, 1257.
684 ---> There are 2 spaces between 2 a and 3 word "Cambia sul canale (Ctrl + Z)"
927 ---> With "get" do you mean "download"? If yes It's correct
1038 ---> Instead to write "...." I wrote what does the command (Extract compressed file)
1224 ---> Must be "Programma per riprodurre gli streams:"
1257 ---> It's correct...

**Comment by DYefremov** [comment]
Hi,

> Italian is a very verbose language compared to English, so it isn't better use abbreviated names.

This increases the space occupied for the column. And many users find it redundant.  This also applies to 1038. Examples: Reloading... Removing... etc. 
1224 is not exactly a program. This is library or framework. 
927 - in this case similar to 'receive'

**Comment by mapi68** [comment]
I have changed many things of old translation because many strings was made with Google Translator and I did understand a very little of DemonEditor so I used before in English. I think that now people understand  ALL: **I translate sense of strings, not single words,** and I try to make a translation that all people understand!!!

**Comment by DYefremov** [comment]
Personally, I don't see any big problems here. Especially using a different language. BUT, I am faced with the fact that many users very often have completely opposite meanings about how something should look and work.

**Pull request closed without merging**
