### PR TITLE
Update

### PR DESCRIPTION
**Pull request by wwns**

### CODE REVIEW

**Comment by wwns** [comment]
corrected and updated translation

**Comment by DYefremov** [comment]
[.po](https://github.com/DYefremov/DemonEditor/pull/8/commits/834df047f1c8560dce0f667985a04f5fef3cb7e6) file contains partially Russian translation. Please make changes with single commit for *.po file only, if possible. And make Pull request just for this commit in the only one brunch(if you use mac, the for experimental-mac). I'll do the rest. Thanks.

**Comment by wwns** [comment]
Hi
I don't understand this github, I'm sorry if I do something wrong.
Regards
Wieslaw

> Wiadomość napisana przez Dmitriy Yefremov <notifications@github.com> w dniu 14.02.2020, o godz. 15:47:
> 
> .po <https://github.com/DYefremov/DemonEditor/pull/8/commits/834df047f1c8560dce0f667985a04f5fef3cb7e6> file contains partially Russian translation. Please make changes with single commit for *.po file only, if possible. And make Pull request just for this commit in the only one brunch(if you use mac, the for experimental-mac). I'll do the rest. Thanks.

**Comment by DYefremov** [comment]
Hi,
Nothing terrible. Just change the .po file for the Polish language and it is advisable to make a request only for this commit.
For example:
[here](https://stackoverflow.com/questions/14034718/include-only-specific-commits-in-a-pull-request) or [here](https://stackoverflow.com/questions/5256021/send-a-pull-request-on-github-for-only-latest-commi)
Good luck
Dmitriy

**Pull request closed without merging**
